import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { Provider } from "@/lib/fetcher-core/provider"
import "react-responsive-carousel/lib/styles/carousel.min.css"
import { Toaster } from "react-hot-toast"

const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <>
              {children}
              <Toaster />
            </>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  )
}
